version: "3.4"

networks:
  payment:
    driver: bridge

services:
  # dev-refresh service will start up a rewards server bound to host port 3343
  # which allows one to do `docker restart rewards-dev-refresh` when the user
  # wants to "restart" the service running new code.  This is especially helpful
  # when you hook it up to `fswatch` type utilities, causing a re-run of `go run`
  # every time a file changes.
  payment-dev-refresh:
    container_name: payment-dev-refresh
    image: golang:1.14.4
    ports:
      - "3353:3353"
      - "6061:6061"
    command: "go run main.go serve payment rest"
    volumes:
      - ./:/src
    working_dir: /src
    networks:
      - payment
      - grant
    depends_on:
      - postgres
    environment:
      - PPROF_ENABLED
      - MIGRATE=true
      - ENV=local
      - ADDR=:3353
      - DATABASE_URL=postgres://grants:password@postgres/grants?sslmode=disable
      - RO_DATABASE_URL=postgres://grants:password@postgres/grants?sslmode=disable
      - UPHOLD_ACCESS_TOKEN
